/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e878504d-4e0f-4960-ba8d-90100ec48bbe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rePPPXWBG",
    "aws_user_pools_web_client_id": "2nb41m54qcas1e5epg5lt9dmip",
    "oauth": {}
};


export default awsmobile;
